In [1]:
import numpy as np

In [2]:
A = np.array([[1, -1j, 0], [1j, 1, 0], [0, 0, 1]])

In [3]:
A

array([[ 1.+0.j, -0.-1.j,  0.+0.j],
       [ 0.+1.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j]])

In [4]:
A.dtype

dtype('complex128')

### Spectral decomposition

In [5]:
# `w` contains the list of eigenvalues, and `v` stores the eigenvectors
w, v = np.linalg.eig(A)

In [6]:
w

array([2.+0.j, 0.+0.j, 1.+0.j])

In [7]:
v

array([[-0.        -0.70710678j,  0.70710678+0.j        ,
         0.        +0.j        ],
       [ 0.70710678+0.j        ,  0.        -0.70710678j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         1.        +0.j        ]])

In [8]:
# eigenvector relation test
# (`@` performs a matrix-matrix multiplication: this gets translated to `numpy.matmul`)
np.allclose(A @ v, v @ np.diag(w))

True

### Singular value decomposition

In [9]:
# Compared to the notation in the lecture, `vh` stores the conjugate-transpose matrix of V.
u, s, vh = np.linalg.svd(A)

In [10]:
# singular values
s

array([2.00000000e+00, 1.00000000e+00, 3.35470445e-17])

In [11]:
# `u` unitary test (should be numerically zero)
np.linalg.norm(u @ u.conj().T - np.identity(3))

5.438959822042073e-16

In [12]:
# `vh` unitary test (should be numerically zero)
np.linalg.norm(vh @ vh.conj().T - np.identity(3))

0.0

In [13]:
# SVD relation test
# (`u * s` scales the columns in `u` by the singular values, which is equivalent to multiplying `u` with `np.diag(s)`)
np.allclose(A, (u * s) @ vh)

True